### PR TITLE
OSD-6853: CatalogSource by digest

### PR DESCRIPTION
**Pull request by 2uasimojo**
[OSD-6853](https://issues.redhat.com/browse/OSD-6853)

### CODE REVIEW

**Comment by 2uasimojo** [comment]
/hold

Depends-On: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/17954

**Comment by jharrington22** [comment]
@yithian if you could review please.

**Review by jharrington22 — APPROVED** [review]

**Comment by 2uasimojo** [comment]
> @yithian if you could review please.

Dustin got it.

**Pull request merged**
