### PR TITLE
added fields to certificate request types

### PR DESCRIPTION
**Pull request by ninataneja**
Added fields for API URL and Web Console URL in certificate request spec in certificaterequest_types.go. The API URL is the URL where the cluster's API can be accessed. The Web Console URL is the URL for the cluster's web console. I also updated the generated code for the certificate request types. The added fields will be used to access certificate serial number data to check whether the certificates on the cluster and on secret on the hive match. A match will ensure that the latest certificates are on the cluster.

### CODE REVIEW

**Comment by tparikh** [comment]
@ninataneja Please add description to the PR.

/hold

**Comment by fahlmant** [comment]
@ninataneja Could add a short description of the changes you made and why?

**Pull request merged**
