### PR TITLE
Update CRD formatting And Boilerplate Generated Files

### PR DESCRIPTION
**Pull request by dustman9000**
These changes will allow PROW to pass (PR: https://github.com/openshift/release/pull/14354) based on new boilerplate make targets around lint/validate.

### CODE REVIEW

**Comment by 2uasimojo** [comment]
/lgtm

Ready to un-WIP?

**Review by 2uasimojo — COMMENTED** [review]
/lgtm

**Review by jharrington22 — APPROVED** [review]
/lgtm

**Pull request merged**
