### PR TITLE
adding config for additional api endpoint to default certs, rh-api.cl…

### PR DESCRIPTION
**Pull request by c-e-brumm**
…uster. Shortening time waiting on DNS propagation from 60 to 30 seconds.

### CODE REVIEW

**Comment by dofinn** [comment]
Is there justification anywhere regarding the shorter time for propagation validation?

**Comment by c-e-brumm** [comment]
@dofinn scalability. Each name in the cert is a 1 minute wait timer. If we get to 4 names per control plane cert (we will) then we're waiting 4 minutes for certman to complete the request. This will keep that lower.

**Comment by cblecker** [comment]
/lgtm
/approve
/hold

Is this ready to go in, @c-e-brumm? If so, feel free to `/hold cancel`

**Pull request merged**
