### PR TITLE
Add test script for certman-operator

### PR DESCRIPTION
**Pull request by dak1n1**
In order to merge PR #103, create a test script for repeatable testing using minikube.

### CODE REVIEW

**Comment by jharrington22** [comment]
@dak1n1 are all these dependencies related to the code you are committing here?

**Comment by dak1n1** [comment]
@jharrington22 the code vendored in this PR is for this file, which is a part of the GCP PR that I'm breaking off into smaller PRs.

```
hack/certbot-to-pem/main.go
```

The certbot utility isn't something that SREP uses, but I think @mjudeikis uses it for development purposes. Here's a link to their docs. https://certbot.eff.org/docs/intro.html

Now that I'm looking at it, I'm not sure it belongs in this repo, since it's a stand-alone utility not needed for certman-operator development.

**Comment by dak1n1** [comment]
After talking with @c-e-brumm , we decided not to accept the utility `hack/certbot-to-pem/main.go` and related vendor files. So I'll remove the vendoring from this PR and just submit the test script for certman-operator. I'll continue grabbing the pieces of GCP functionality from the original PR.

**Pull request merged**
