### PR TITLE
Add core maintainers to reviewer and approver in OWNERS

### PR DESCRIPTION
**Pull request by tparikh**
Reverts changes made to OWNERS file.
Add tparikh as approver and reviewer.
Add fahlmant as reviewer.
Team leads are already part of reviewer and approver.

Signed-off-by: Tejas Parikh <tparikh@redhat.com>

### CODE REVIEW

**Comment by jewzaam** [comment]
Our guideline had the OWNERS to be what this PR is based on.  We'd like to use this PR to discuss and decide on what adjustments need to be made to the guideline.

In summary, it's adding the core maintainer as an owner and additional maintainers as reviewers.  This enables PRs to be approved by the core team w/o having a bottleneck on team leads (Matt and myself).  Team leads are still available to approve if needed.

I propose our guideline be adjusted to add one additional owner to be the core maintainer and any number of additional reviewers.  We apply this on all the SRE repos.

I will tag folks in slack to get some commentary.

**Comment by jharrington22** [comment]
To be clear thats a +1 for the maintainer being added to the owner file

**Comment by aweiteka** [comment]
+1 lgtm
I recommend broadening, over time, the list of reviewers to encourage more folks to contribute in that way. Active reviewers are essential to the health of any fast-moving project. We don't know which ones will become popular. Today's active reviewers become tomorrow's maintainers.

**Comment by fahlmant** [comment]
:+1: To adding maintainers to the OWNERS file

**Comment by mwoodson** [comment]
I am in favor of having the maintainer be an owner.  I am generally in favor of having more people rather than less to be reviewers and owners.  For now +1 to maintainers to be owners.

This does silo us a bit, and reorganizing the maintainers may need to happen on occasion, but we can work through this.

**Comment by jewzaam** [comment]
I think changes to OWNERS won't be too rough, it's a PR like this one.  As long as we don't have all the maintainers drop out all at once it should be straight forward

**Comment by jewzaam** [comment]
I've tweaked our guideline to indicate to add the following:

- 1 additional approver, the core maintainer
- 1 or more additional reviewers, the core maintainer and additional key contributors

/approve

**Pull request merged**
